├── 00_Scope_and_Assumptions.md
├── 01_Executive_Brief.md
├── 02_Threat_Landscape_Context.md
├── 03_Attack_Scenario_Model.md
├── 04_Technical_Tradecraft_Analysis.md
├── 05_MITRE_ATTCK_Mapping.md
├── 06_Systemic_Risk_Assessment.md
├── 07_Detection_Opportunities.md
├── 08_Strategic_Recommendations.md
└── Appendix_A_Simulated_Indicators.md
